import { Artwork } from '../types';

// Recent Works
export const recentWorksData: Artwork[] = [
  {
    id: 'rw-1',
    title: 'Basket with Lemons',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'A beautiful still life featuring fresh lemons in a woven basket, painted in the style of Dutch Masters.',
    imagePath: '/images/paintings/recent-works/basket-with-lemons/anne-songhurst--basket_with_lemons_10x10.jpg',
    slug: 'basket-with-lemons',
    featured: true,
    tags: ['still life', 'lemons', 'basket', 'contemporary']
  },
  {
    id: 'rw-2',
    title: 'Cheese and Grapes',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'An elegant composition of artisanal cheese and fresh grapes.',
    imagePath: '/images/paintings/recent-works/cheese-and-grapes/anne-songhurst-cheese-and-grapes-10x12-.jpg',
    slug: 'cheese-and-grapes',
    tags: ['still life', 'cheese', 'grapes', 'food']
  },
  {
    id: 'rw-3',
    title: 'Chinese Bowl with Pears',
    category: 'recent-works',
    year: 2023,
    dimensions: '8" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Delicate pears arranged in an antique Chinese porcelain bowl.',
    imagePath: '/images/paintings/recent-works/chinese-bowl-with-pears/anne-songhurst-chinese-bowl-with-pears-8x10.jpg',
    slug: 'chinese-bowl-with-pears',
    tags: ['still life', 'pears', 'chinese porcelain', 'antique']
  },
  {
    id: 'rw-4',
    title: 'Chinese Caddy with Lemons',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Bright lemons displayed with an antique Chinese tea caddy.',
    imagePath: '/images/paintings/recent-works/chinese-caddy-with-lemons/anne-songhurst-chinese-caddy-with-lemons-10x10.jpg',
    slug: 'chinese-caddy-with-lemons',
    tags: ['still life', 'lemons', 'chinese', 'tea caddy']
  },
  {
    id: 'rw-5',
    title: 'Chinese Porcelain with Lemons',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'A harmonious arrangement of lemons with fine Chinese porcelain.',
    imagePath: '/images/paintings/recent-works/chinese-porcelain-with-lemons/anne-songhurst-chinese-porcelain-with-lemons-12x12.jpg',
    slug: 'chinese-porcelain-with-lemons',
    tags: ['still life', 'lemons', 'chinese porcelain', 'ceramic']
  },
  {
    id: 'rw-6',
    title: 'Cockerel Jug with Eggs',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Farm fresh eggs alongside a charming cockerel-decorated jug.',
    imagePath: '/images/paintings/recent-works/cockerel-jug-with-eggs/anne-songhurst-cockerel-jug-with-eggs-10x12.jpg',
    slug: 'cockerel-jug-with-eggs',
    featured: true,
    tags: ['still life', 'eggs', 'cockerel', 'farm fresh']
  },
  {
    id: 'rw-7',
    title: 'Copper Pan with Clementines',
    category: 'recent-works',
    year: 2023,
    dimensions: '8" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Sweet clementines arranged in a burnished copper pan.',
    imagePath: '/images/paintings/recent-works/copper-pan-with-clementines/anne-songhurst-copper-pan-with-clementines-8x10.jpg',
    slug: 'copper-pan-with-clementines',
    tags: ['still life', 'clementines', 'copper', 'citrus']
  },
  {
    id: 'rw-8',
    title: 'Copper Pot with Plums',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Rich purple plums displayed in an antique copper pot.',
    imagePath: '/images/paintings/recent-works/copper-pot-with-plums/anne-songhurst-copper-pot-with-plums-12x10.jpg',
    slug: 'copper-pot-with-plums',
    tags: ['still life', 'plums', 'copper', 'antique']
  },
  {
    id: 'rw-9',
    title: 'Enamelware with Tomatoes',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Fresh tomatoes in vintage enamelware, capturing summer abundance.',
    imagePath: '/images/paintings/recent-works/enamelware-with-tomatoes/anne-songhurst--enamelware-with-tomatoes-12x12-.jpg',
    slug: 'enamelware-with-tomatoes',
    tags: ['still life', 'tomatoes', 'enamelware', 'vintage']
  },
  {
    id: 'rw-10',
    title: 'Figs on a Silver Plate',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Ripe figs elegantly arranged on polished silver plate.',
    imagePath: '/images/paintings/recent-works/figs-on-a-silver-plate/anne_-songhurst_-figs_on_a_silver_plate_10x12.jpg',
    slug: 'figs-on-silver-plate',
    tags: ['still life', 'figs', 'silver', 'elegant']
  },
  {
    id: 'rw-11',
    title: 'Mandarins',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Vibrant mandarin oranges capturing the essence of winter citrus.',
    imagePath: '/images/paintings/recent-works/mandarins/anne-songhurst-mandarins-12x12.jpg',
    slug: 'mandarins',
    tags: ['still life', 'mandarins', 'citrus', 'winter']
  },
  {
    id: 'rw-12',
    title: 'Ming Bowl with Eggs',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: false,
    description: 'Farm eggs nestled in an antique Ming dynasty bowl.',
    imagePath: '/images/paintings/recent-works/ming-bowl-with-eggs/f2738aca-c03b-4c0b-abb5-796d3475f730.jpg',
    slug: 'ming-bowl-with-eggs',
    tags: ['still life', 'eggs', 'ming', 'antique']
  },
  {
    id: 'rw-13',
    title: 'Peaches and White Wine',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Summer peaches paired with a glass of white wine.',
    imagePath: '/images/paintings/recent-works/peaches-and-white-wine/anne-songhurst-peaches-and-white-wine-10x12-.jpg',
    slug: 'peaches-and-white-wine',
    featured: true,
    tags: ['still life', 'peaches', 'wine', 'summer']
  },
  {
    id: 'rw-14',
    title: 'Redcurrants and Silverware',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Jewel-like redcurrants with polished silver serving pieces.',
    imagePath: '/images/paintings/recent-works/redcurrants-and-silverware/anne-songhurst-redcurrants-and-silverware-12x12-.jpg',
    slug: 'redcurrants-and-silverware',
    tags: ['still life', 'redcurrants', 'silverware', 'berries']
  },
  {
    id: 'rw-15',
    title: 'Silver Jug with Apricots',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Golden apricots complemented by reflective silver surfaces.',
    imagePath: '/images/paintings/recent-works/silver-jug-with-apricots/anne-songhurst-silver-jug-with-apricots-10x12-.jpg',
    slug: 'silver-jug-with-apricots',
    tags: ['still life', 'apricots', 'silver', 'reflections']
  },
  {
    id: 'rw-16',
    title: 'Silver Jug with Blackberries',
    category: 'recent-works',
    year: 2023,
    dimensions: '8" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Dark blackberries creating contrast with polished silver.',
    imagePath: '/images/paintings/recent-works/silver-jug-with-blackberries/anne-songhurst-silver-jug-with-blackberries-8x10.jpg',
    slug: 'silver-jug-with-blackberries',
    tags: ['still life', 'blackberries', 'silver', 'contrast']
  },
  {
    id: 'rw-17',
    title: 'Silver Jug with Cherries',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Fresh cherries alongside a polished silver jug, showcasing reflective surfaces.',
    imagePath: '/images/paintings/recent-works/silver-jug-with-cherries/anne-songhurst-silver-jug-with-cherries-10x10-.jpg',
    slug: 'silver-jug-with-cherries',
    tags: ['still life', 'cherries', 'silver', 'reflections']
  },
  {
    id: 'rw-18',
    title: 'Silver Jug with Olives',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Mediterranean olives displayed with elegant silverware.',
    imagePath: '/images/paintings/recent-works/silver-jug-with-olives/9b8f7868-8a02-41b4-b6c3-7c79a4aeac30.jpg',
    slug: 'silver-jug-with-olives',
    tags: ['still life', 'olives', 'silver', 'mediterranean']
  },
  {
    id: 'rw-19',
    title: 'Silver Tankard with Lemons',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Bright lemons paired with an antique silver tankard.',
    imagePath: '/images/paintings/recent-works/silver-tankard-with-lemons/silver-tankard-with-lemons-12x12.jpg',
    slug: 'silver-tankard-with-lemons',
    tags: ['still life', 'lemons', 'silver', 'tankard']
  },
  {
    id: 'rw-20',
    title: 'Silverware with Nectarines',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Juicy nectarines accompanied by polished silver serving pieces.',
    imagePath: '/images/paintings/recent-works/silverware-with-nectarines/anne-songhurst-silverware-with-nectarines-12x10-.jpg',
    slug: 'silverware-with-nectarines',
    tags: ['still life', 'nectarines', 'silverware', 'summer fruit']
  },
  {
    id: 'rw-21',
    title: 'Snowdrops and Blue Glass',
    category: 'recent-works',
    year: 2024,
    dimensions: '8" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Delicate snowdrops in blue glass, heralding spring\'s arrival.',
    imagePath: '/images/paintings/recent-works/snowdrops-and-blue-glass/9c13b800-6e7b-4b0f-8862-b6d7d16d3342.jpg',
    slug: 'snowdrops-and-blue-glass',
    tags: ['still life', 'snowdrops', 'blue glass', 'spring']
  },
  {
    id: 'rw-22',
    title: 'Still Life with Green Glass',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 16"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'An elegant composition featuring green glass vessels and natural elements.',
    imagePath: '/images/paintings/recent-works/still-life-with-green-glass/still-life-with-green-glass-12x16.jpg',
    slug: 'still-life-with-green-glass',
    tags: ['still life', 'green glass', 'vessels', 'elegant']
  },
  {
    id: 'rw-23',
    title: 'Stoneware Flagon with Apples',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 16"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: false,
    description: 'Crisp apples arranged with traditional stoneware pottery.',
    imagePath: '/images/paintings/recent-works/stoneware-flagon-with-apples/b923f897-aff8-4d06-883f-cfc92b6a5cf4.jpg',
    slug: 'stoneware-flagon-with-apples',
    tags: ['still life', 'apples', 'stoneware', 'pottery']
  },
  {
    id: 'rw-24',
    title: 'Stoneware Flagon with Pears',
    category: 'recent-works',
    year: 2023,
    dimensions: '14" x 18"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Elegant pears with rustic stoneware, bridging traditional and contemporary.',
    imagePath: '/images/paintings/recent-works/stoneware-flagon-with-pears/e0127fdc-1a3d-48c2-8a3f-e2d6099d3831.jpg',
    slug: 'stoneware-flagon-with-pears',
    tags: ['still life', 'pears', 'stoneware', 'rustic']
  },
  {
    id: 'rw-25',
    title: 'Stoneware Jar with Peaches',
    category: 'recent-works',
    year: 2023,
    dimensions: '8" x 8"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Summer peaches nestled beside handcrafted stoneware.',
    imagePath: '/images/paintings/recent-works/stoneware-jar-with-peaches/anne-songhurst-stoneware-jar-with-peaches-8x8-.jpg',
    slug: 'stoneware-jar-with-peaches',
    tags: ['still life', 'peaches', 'stoneware', 'summer']
  },
  {
    id: 'rw-26',
    title: 'Tudric Tankard with Apples',
    category: 'recent-works',
    year: 2023,
    dimensions: '12" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Crisp apples with an Arts and Crafts Tudric pewter tankard.',
    imagePath: '/images/paintings/recent-works/tudric-tankard-with-apples/anne-songhurst-tudric-tankard-with-apples-12x12.jpg',
    slug: 'tudric-tankard-with-apples',
    tags: ['still life', 'apples', 'tudric', 'pewter', 'arts and crafts']
  },
  {
    id: 'rw-27',
    title: 'Wine Bottle with Lemons',
    category: 'recent-works',
    year: 2023,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Fresh lemons paired with an elegant wine bottle in natural light.',
    imagePath: '/images/paintings/recent-works/wine-bottle-with-lemons/anne-songhurst-wine-bottle-with-lemons-10x12-.jpg',
    slug: 'wine-bottle-with-lemons',
    tags: ['still life', 'lemons', 'wine bottle', 'natural light']
  }
];

// Trompe L'Oeil
export const trompeLoeilData: Artwork[] = [
  {
    id: 'tl-1',
    title: 'Cabinet of Curios',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '16" x 20"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'A masterful trompe-l\'oeil cabinet filled with fascinating curiosities and collectibles.',
    imagePath: '/images/paintings/trompe-loeil/cabinet-of-curios/cabinet-of-curios.jpg',
    slug: 'cabinet-of-curios',
    tags: ['trompe loeil', 'cabinet', 'curios', 'collectibles']
  },
  {
    id: 'tl-2',
    title: 'Cabinet of Memories',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '18" x 24"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'A trompe-l\'oeil painting depicting a cabinet filled with treasured objects and memories.',
    imagePath: '/images/paintings/trompe-loeil/cabinet-of-memories/anne-songhurst-cabinet-of-memories.jpg',
    slug: 'cabinet-of-memories',
    featured: true,
    tags: ['trompe loeil', 'cabinet', 'memories', 'objects']
  },
  {
    id: 'tl-3',
    title: 'Cabinet of Miniatures',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '14" x 18"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Delicate miniature objects displayed in a trompe-l\'oeil cabinet setting.',
    imagePath: '/images/paintings/trompe-loeil/cabinet-of-miniatures/anne-songhurst-cabinet-of-miniatures.jpg',
    slug: 'cabinet-of-miniatures',
    tags: ['trompe loeil', 'cabinet', 'miniatures', 'delicate']
  },
  {
    id: 'tl-4',
    title: 'Cabinet with Apples',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '12" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Fresh apples arranged in a trompe-l\'oeil cabinet shelf composition.',
    imagePath: '/images/paintings/trompe-loeil/cabinet-with-apples/cabinet-with-apples-12x12.jpg',
    slug: 'cabinet-with-apples',
    tags: ['trompe loeil', 'cabinet', 'apples', 'fresh fruit']
  },
  {
    id: 'tl-5',
    title: 'Cabinet with Delftware',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '12" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: false,
    description: 'Beautiful Delft porcelain pieces displayed in a realistic cabinet setting.',
    imagePath: '/images/paintings/trompe-loeil/cabinet-with-delftware/anne-songhurst-cabinet-with-delftware-12x10.jpg',
    slug: 'cabinet-with-delftware',
    tags: ['trompe loeil', 'cabinet', 'delftware', 'porcelain']
  },
  {
    id: 'tl-6',
    title: 'Chinese Blue and White',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '16" x 20"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Exquisite Chinese blue and white porcelain arranged in trompe-l\'oeil style.',
    imagePath: '/images/paintings/trompe-loeil/chinese-blue-and-white/chinese-blue-and-white.jpg',
    slug: 'chinese-blue-and-white',
    tags: ['trompe loeil', 'chinese', 'blue and white', 'porcelain']
  },
  {
    id: 'tl-7',
    title: 'Chinese Porcelain',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '14" x 16"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'A collection of fine Chinese porcelain pieces in realistic detail.',
    imagePath: '/images/paintings/trompe-loeil/chinese-porcelain/chinese-porcelain.jpg',
    slug: 'chinese-porcelain',
    tags: ['trompe loeil', 'chinese', 'porcelain', 'collection']
  },
  {
    id: 'tl-8',
    title: 'Delftware Collection',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '18" x 22"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'An extensive collection of Dutch Delftware displayed with museum-quality precision.',
    imagePath: '/images/paintings/trompe-loeil/delftware-collection/delftware-collection.jpg',
    slug: 'delftware-collection',
    featured: true,
    tags: ['trompe loeil', 'delftware', 'dutch', 'collection']
  },
  {
    id: 'tl-9',
    title: 'Ming Jarlet',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '5" x 5"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'A small but detailed trompe-l\'oeil study of an antique Ming jarlet.',
    imagePath: '/images/paintings/trompe-loeil/ming-jarlet/anne-songhurst-ming-jarlet-5x5.jpg',
    slug: 'ming-jarlet',
    tags: ['trompe loeil', 'ming', 'porcelain', 'miniature']
  },
  {
    id: 'tl-10',
    title: 'Oriental Collection',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '16" x 20"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: false,
    description: 'A comprehensive trompe-l\'oeil display of oriental ceramics and artifacts.',
    imagePath: '/images/paintings/trompe-loeil/oriental-collection/anne-songhurst-oriental-collection.jpg',
    slug: 'oriental-collection',
    tags: ['trompe loeil', 'oriental', 'ceramics', 'collection']
  },
  {
    id: 'tl-11',
    title: 'Spode Italian',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '8" x 6"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Classic Spode Italian pattern ceramics in trompe-l\'oeil style.',
    imagePath: '/images/paintings/trompe-loeil/spode-italian/spode-italian-8x6.jpg',
    slug: 'spode-italian',
    tags: ['trompe loeil', 'spode', 'italian', 'ceramic']
  },
  {
    id: 'tl-12',
    title: 'Willow Jug and Bowl',
    category: 'trompe-loeil',
    year: 2022,
    dimensions: '8" x 6"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Traditional willow pattern jug and bowl in meticulous trompe-l\'oeil detail.',
    imagePath: '/images/paintings/trompe-loeil/willow-jug-and-bowl/willow-jug-and-bowl-8x6.jpg',
    slug: 'willow-jug-and-bowl',
    tags: ['trompe loeil', 'willow pattern', 'jug', 'bowl']
  },
  {
    id: 'tl-13',
    title: 'Wonky\'s Niche in my Memory',
    category: 'trompe-loeil',
    year: 2021,
    dimensions: '10" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'A personal trompe-l\'oeil tribute featuring cherished objects and memories.',
    imagePath: '/images/paintings/trompe-loeil/wonkys-niche-in-my-memory/wonkys-niche-in-my-memory-10x10.jpg',
    slug: 'wonkys-niche-in-my-memory',
    featured: true,
    tags: ['trompe loeil', 'personal', 'memories', 'tribute']
  }
];

// Archive
export const archiveData: Artwork[] = [
  {
    id: 'ar-1',
    title: 'Basket with Eggs',
    category: 'archive',
    year: 2020,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'Sold',
    available: false,
    description: 'An early work featuring farm-fresh eggs in a traditional woven basket.',
    imagePath: '/images/paintings/archive/basket-with-eggs/anne-songhurst-basket-with-eggs-10x12.jpg',
    slug: 'basket-with-eggs-archive',
    tags: ['still life', 'eggs', 'basket', 'farm fresh']
  },
  {
    id: 'ar-2',
    title: 'Celadon Bowl with Eggs',
    category: 'archive',
    year: 2020,
    dimensions: '10" x 10"',
    medium: 'Oil on canvas',
    price: 'Sold',
    available: false,
    description: 'Eggs displayed in a beautiful celadon ceramic bowl.',
    imagePath: '/images/paintings/archive/celadon-bowl-with-eggs/anne-songhurst-celadon-bowl-with-eggs-10x10.jpg',
    slug: 'celadon-bowl-with-eggs',
    tags: ['still life', 'eggs', 'celadon', 'ceramic']
  },
  {
    id: 'ar-3',
    title: 'Cider Flagon with Pears',
    category: 'archive',
    year: 2019,
    dimensions: '14" x 18"',
    medium: 'Oil on canvas',
    price: 'Sold',
    available: false,
    description: 'A signature piece featuring pears with a traditional cider flagon from John Leach Pottery.',
    imagePath: '/images/paintings/archive/cider-flagon-with-pears/anne-songhurst-cider-flagon-with-pears-14x18.jpg',
    slug: 'cider-flagon-with-pears-archive',
    featured: true,
    tags: ['still life', 'pears', 'cider flagon', 'pottery']
  },
  {
    id: 'ar-4',
    title: 'Creamware Basket with Cherries',
    category: 'archive',
    year: 2020,
    dimensions: '10" x 10"',
    medium: 'Oil on canvas',
    price: 'Sold',
    available: false,
    description: 'Sweet cherries arranged in an antique creamware basket.',
    imagePath: '/images/paintings/archive/creamware-basket-with-cherries/anne-songhurst-creamware-basket-with-cherries-10x10.jpg',
    slug: 'creamware-basket-with-cherries',
    tags: ['still life', 'cherries', 'creamware', 'basket']
  },
  {
    id: 'ar-5',
    title: 'Free Range',
    category: 'archive',
    year: 2019,
    dimensions: '12" x 12"',
    medium: 'Oil on canvas',
    price: 'Sold',
    available: false,
    description: 'A celebration of farm life with fresh eggs in natural setting.',
    imagePath: '/images/paintings/archive/free-range/anne-songhurst-free-range-12x12.jpg',
    slug: 'free-range',
    featured: true,
    tags: ['still life', 'eggs', 'farm life', 'natural']
  },
  {
    id: 'ar-6',
    title: 'Glass Jug with Snowdrops',
    category: 'archive',
    year: 2020,
    dimensions: '8" x 8"',
    medium: 'Oil on canvas',
    price: 'Sold',
    available: false,
    description: 'Delicate snowdrops in a clear glass jug, capturing early spring.',
    imagePath: '/images/paintings/archive/glass-jug-with-snowdrops/anne-songhurst-glass-jug-with-snowdrops-8x8.jpg',
    slug: 'glass-jug-with-snowdrops',
    tags: ['still life', 'snowdrops', 'glass', 'spring']
  },
  {
    id: 'ar-7',
    title: 'Westerwald Jug with Plums',
    category: 'archive',
    year: 2019,
    dimensions: '12" x 16"',
    medium: 'Oil on canvas',
    price: 'Sold',
    available: false,
    description: 'Purple plums with traditional German Westerwald stoneware jug.',
    imagePath: '/images/paintings/archive/westerwald-jug-with-plums/anne-songhurst-westerwald-jug-with-plums-12x16.jpg',
    slug: 'westerwald-jug-with-plums',
    tags: ['still life', 'plums', 'westerwald', 'stoneware']
  }
];

// Off the Easel
export const offTheEaselData: Artwork[] = [
  {
    id: 'ote-1',
    title: 'Brockalee Farm Eggs',
    category: 'off-the-easel',
    year: 2024,
    dimensions: '8" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Fresh eggs from Brockalee Farm, painted directly from life.',
    imagePath: '/images/paintings/off-the-easel/brockalee-farm-eggs/4fe5e26d-ccc9-403e-9304-4ffd06e65c5b.jpg',
    slug: 'brockalee-farm-eggs',
    featured: true,
    tags: ['still life', 'eggs', 'farm fresh', 'contemporary']
  },
  {
    id: 'ote-2',
    title: 'Chinese Porcelain with Apricots',
    category: 'off-the-easel',
    year: 2024,
    dimensions: '10" x 12"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Ripe apricots displayed with antique Chinese porcelain.',
    imagePath: '/images/paintings/off-the-easel/chinese-porcelain-with-apricots/fbec482e-e806-458e-a4b6-3b8ed52ed4af.jpg',
    slug: 'chinese-porcelain-with-apricots',
    tags: ['still life', 'apricots', 'chinese porcelain', 'fruit']
  },
  {
    id: 'ote-3',
    title: 'Cornishware Pot with Lemons',
    category: 'off-the-easel',
    year: 2024,
    dimensions: '10" x 8"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Bright lemons with classic blue and white Cornishware pottery.',
    imagePath: '/images/paintings/off-the-easel/cornishware-pot-with-lemons/aca461fb-c56a-4648-8369-78028deeb4ad.jpg',
    slug: 'cornishware-pot-with-lemons',
    tags: ['still life', 'lemons', 'cornishware', 'pottery']
  },
  {
    id: 'ote-4',
    title: 'Harrison Bowl with Eggs',
    category: 'off-the-easel',
    year: 2024,
    dimensions: '9" x 11"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Farm fresh eggs nestled in a handcrafted Harrison pottery bowl.',
    imagePath: '/images/paintings/off-the-easel/harrison-bowl-with-eggs/1df2b51b-da4a-4423-a198-4446d9595661.jpg',
    slug: 'harrison-bowl-with-eggs',
    tags: ['still life', 'eggs', 'harrison pottery', 'handcrafted']
  },
  {
    id: 'ote-5',
    title: 'Strawberries in a Silver Bowl',
    category: 'off-the-easel',
    year: 2024,
    dimensions: '8" x 10"',
    medium: 'Oil on canvas',
    price: 'POA',
    available: true,
    description: 'Fresh summer strawberries gleaming in a polished silver bowl.',
    imagePath: '/images/paintings/off-the-easel/strawberries-in-a-silver-bowl/c306261e-06db-4136-9a59-c83c975fbbb5.jpg',
    slug: 'strawberries-in-silver-bowl',
    featured: true,
    tags: ['still life', 'strawberries', 'silver', 'summer']
  }
];

export const allArtworks: Artwork[] = [
  ...recentWorksData,
  ...trompeLoeilData,
  ...archiveData,
  ...offTheEaselData
];

export const featuredArtworks = allArtworks.filter(artwork => artwork.featured);
export const availableArtworks = allArtworks.filter(artwork => artwork.available);